import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ session }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>N Rich Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        <p>Welcome to NRich Finance. Unlock the doors to a world of educational opportunities with an international student loan, sign up today and take the first step towards achieving your dreams.</p>
      </div>
    </div>
  );
}
